language: node_js
node_js:
  - stable
  - 8
  - 6
  - node #latest

branches:
  only:
    - master

cache: npm

install:
  - npm install

script:
  - npm test
  - npm run lint
  - npm audit
  - npm outdated
