language: node_js
node_js:
  - stable
  - 8
  - node #latest

branches:
  only:
    - master

cache: npm

install:
  - npm install

script:
  - npm run lint
  - npm run test-with-coverage # run test with coverage report
  - npm audit
  - npm outdated

after_success:
  - npm run publish-coverage

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
